---
version: 2
jobs:
  build:
    machine: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: run1
          command: |
            uname -a
      #- run:
      #    name: run2
      #    command: |
      #      systemctl status
      - run:
          name: run3
          command: |
            ps ax

# vim:ts=2:sw=2:et:
