---
version: 2
jobs:
  build:
    machine: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: run1
          command: |
            uname -a
      #- run:
      #    name: run2
      #    command: |
      #      systemctl status
      - run:
          name: run3
          command: |
            ps ax
      - run:
          name: run4
          command: |
            cat /proc/cpuinfo
      - run:
          name: run5
          command: |
            docker version
      - run:
          name: run6
          command: |
            export JUJUJU=LELELE >> $BASH_ENV
      - run:
          name: run7
          command: |
            echo $JUJUJU

# vim:ts=2:sw=2:et:
